language: python

sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - travis_retry pip install tox-travis
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt

script: tox

after_success:
  - coverage run --source=unicheck -m unittest discover -s tests
  - coveralls
